insert into triggerref

values 
('1','Abnormal cranial imaging/IVH-Grade 3 or 4 Head bleed in CICU or NICU','Perinatal','NULL'),
('2','Abrupt medication stop','Patient Care','NULL'),
('3','Acute Dialysis','NULL','NULL'),
('4','Administration of Digoxin Immune Fab (Digibind)','Medication Reversal','medication'),
('5','Administration of Flumazenil (Romazicon) ','Medication Reversal','medication'),
('6','Administration of Oral Vancomycin','NULL','NULL'),
('7','Administration of Oxytocin Agents','NULL','NULL'),
('8','Administration of Protamine Sulfate after Heparin','Coagulation','medication-medication'),
('9','Administration of Romazicon (Flumazenil) > 24 hrs after surgery','NULL','medication'),
('10','Administration of Vitamin K after Warfarin','Coagulation','medication-medication'),
('11','Admission to intensive care Post-operatively','NULL','NULL'),
('12','Amikacin Trough > 20 ug/mL','NULL','NULL'),
('13','Antiemetic Administration','NULL','NULL'),
('14','Antifactor Xa > 0.71','Coagulation','lab'),
('15','AntiXa > 1.5 and Heparin or LMWH administered','Coagulation','labAndMed'),
('16','AntiXa > 1.5 U/mL','NULL','NULL'),
('17','Any code or arrest','NULL','NULL'),
('18','Any death','Patient Care','patient-care'),
('19','Any death intraoperatively or postoperatively','NULL','NULL'),
('20','Any Pain score >= 6','NULL','NULL'),
('21','Bilirubin total > 25 mg/dL','Pediatric','lab'),
('22','BUN > 2 * baseline','Patient Care','NULL'),
('23','Carbamazepine > 20 mcg/ml','Pediatric','lab'),
('24','Clostridium Positive stool','Healthcare Associated Infections','lab'),
('25','Creatinine > 2 * baseline','Renal Injury ','lab-lab'),
('26','Creatinine > 3 * baseline','Renal Injury ','lab-lab'),
('27','Cyclosporin ','NULL','NULL'),
('28','Decrease in Hematocrit (Hct) of 25% or greater  within 48 hrs','NULL','NULL'),
('29','Decrease in Hematocrit (Hct) of 25% or greater within 24 hour time period','NULL','NULL'),
('30','Decrease in Hemoglobin (excluding POC) of 25% or greater within 24 hour time period','Coagulation','NULL'),
('31','Decrease in Hemoglobin (Hgb) of 25% or greater within 24 hour time period','Coagulation','NULL'),
('32','Decrease in Hemoglobin (Hgb) of 25% or greater within 48 hrs','Coagulation','lab-lab'),
('33','Decrease in Hemoglobin (POC) of 25% or greater within 24 hour time period','Coagulation','NULL'),
('34','Decrease in Hemoglobin >=25% post surgery','Coagulation','lab-prereq-prereq'),
('35','Digoxin level > 2.0 mg','NULL','NULL'),
('36','Diphenhydramine (Benedryl) Administration','NULL','NULL'),
('37','ED readmit within 48 hrs after ED discharge','Readmission','NULL'),
('38','ED readmit within 48 hrs after hospital discharge','Readmission','readmission'),
('39','Failed extubation','NULL','NULL'),
('40','Falls','Patient Care','patient-care'),
('41','Free phenytoin','NULL','NULL'),
('42','Gentamicin trough > 4 ug/mL','NULL','NULL'),
('43','Glucose < 50.0 mg/dL or 2.8 mmol/L','Glycemic','NULL'),
('44','Glucose <= 40.0','Glycemic','lab'),
('45','Glucose > 250 mg/dL or 14 mmol/L','Glycemic','NULL'),
('46','Glucose >= 180 back to back','Glycemic','lab-lab'),
('47','Glucose >= 250.0 Back to Back','Glycemic','lab-lab'),
('48','Glucose bolus and patient on Insulin','NULL','NULL'),
('49','Healthcare Associated Infection','NULL','NULL'),
('50','Hospital Admission within 48 hrs after ED discharge','Readmission','readmission'),
('51','Hospital Readmission within 7 days','Readmission','readmission'),
('52','Hospital Readmission within 7 days - Unplanned only','Readmission','readmission'),
('53','Hospital Readmission within 8 - 15 days','Readmission','readmission'),
('54','Hospital Readmission within 8 - 15 days - Unplanned only','Readmission','readmission'),
('55','Hospital Readmission within 16 - 30 days','Readmission','readmission'),
('56','Hospital Readmission within 16 - 30 days - Unplanned only','Readmission','readmission'),
('57','Hospital readmission within 30 days for all surgical procedures','Surgical','readmission'),
('58','Hypoglycemia  and administration of glucagon','NULL','NULL'),
('59','ICU Readmission','Patient Care','NULL'),
('60','ICU Readmission within 24 hours','Patient Care','adt-adt'),
('61','In-hospital Stroke','Patient Care','event-prereq-event'),
('62','Infiltration: Hyaluronidase Administration','Pediatric','medication'),
('63','Infiltration: Nursing IV Documentation','Pediatric','patient-care'),
('64','Infiltration: Phentolamine Administration ','Pediatric','medication'),
('65','INR >4','Coagulation','lab'),
('66','INR >6','Coagulation','lab'),
('67','Intra-operative IV epinephrine, norepinephrine','NULL','NULL'),
('68','Intubation','Patient Care','patient-care'),
('69','Intubation in PACU','Patient Care','patient-care'),
('70','Laxative or stool softeners','NULL','NULL'),
('71','LDH > 140 and BUN > 40','Patient Care','lab-lab'),
('72','Mechanical Ventilation > 24 hours post-operatively','NULL','NULL'),
('73','Mechanical Ventilation > 48 hours post-operatively','NULL','NULL'),
('74','Mom/Baby transfer to a higher level of care','NULL','NULL'),
('75','Narcan Administration','Medication Reversal','medication'),
('76','Nephrotoxic Medications and Rising Creatinine','Renal Injury ','medication'),
('77','Operative Time > 6 hrs','NULL','NULL'),
('78','Operative Time > 6 hrs -= non-cardiac patients','NULL','NULL'),
('79','Opioid MME >20','Pain Management','medication'),
('80','Opioid MME >50','Pain Management','medication'),
('81','Oxcarbamazepine > 45 ug/mL','Pediatric','lab'),
('82','Patient on Insulin  and administration of glucagon','NULL','NULL'),
('83','Patient on Insulin and Glucose < 50 mg/dL or 2.8 mmol/L','NULL','NULL'),
('84','Patient on Insulin and Glucose > 250 mg/dL or 14 mmol/L','NULL','NULL'),
('85','Phenobarbital > 30 ug/mL','Pediatric','lab'),
('86','Phenobarbital > 40 ug/mL','Pediatric','lab'),
('87','Phenytoin > 30 or Free Phenytoin > 3.0 Trigger','Pediatric','lab'),
('88','Platelet','NULL','NULL'),
('89','Pneumonia','NULL','NULL'),
('90','Positive Blood Culture','Healthcare Associated Infections','lab'),
('91','Positive MRSA screen or culture','Healthcare Associated Infections','NULL'),
('92','Positive Urine Culture','Healthcare Associated Infections','lab'),
('93','Possible surgical site infection','NULL','NULL'),
('94','Postoperative MI Trigger','Surgical','event-prereq-event'),
('95','Post-operative increase in Troponin level','NULL','NULL'),
('96','Potassium < =2.0 mmol/L','NULL','NULL'),
('97','Potassium > =6.5 mmol/L','NULL','NULL'),
('98','Potassium > 6.0 and  Sodium Polystyrene (Kayexalate) Given','Medication Reversal','labAndMed'),
('99','Potassium > 6.0 mmol/L','NULL','NULL'),
('100','Potential contrast-induced nephropathy','Renal Injury ','lab-prereq-prereq'),
('101','Pressure Ulcers','Patient Care','patient-care'),
('102','PTT > 100','Coagulation','lab'),
('103','PTT > 100 and Heparin within previous 24 hrs','Coagulation','labAndMed'),
('104','Racemic epinephrine administration after extubation','NULL','NULL'),
('105','Radiology Study for Emboli or DVT','Coagulation','patient-care'),
('106','Radiology Study intraoperatively or in PACU','NULL','NULL'),
('107','Restraint Use','NULL','NULL'),
('108','Return to Surgery','Surgical','event-prereq-event'),
('109','Serum Sodium < 125 mmol/L','NULL','NULL'),
('110','Serum Sodium > 160 mmol/L','NULL','NULL'),
('111','Sodium Polystyrene (Kayexalate) Given','Medication Reversal','NULL'),
('112','Tacrolimus > 20.0','NULL','NULL'),
('113','Administration of terbutaline','Perinatal','medication'),
('114','Time in ED > 6 hours','NULL','NULL'),
('115','Tobramycin Trough > 4','NULL','NULL'),
('116','Transfer to ICU','Patient Care','NULL'),
('117','Transfer to ICU within 4 hours of admission','Patient Care','adt-adt'),
('118','Transfer to ICU within 4 or more hours after admission','Patient Care','adt-adt'),
('119','Transfusion of Blood Products','NULL','NULL'),
('120','Transfusion of Blood Products after surgery','NULL','NULL'),
('121','Valproic acid > 170                    ','Pediatric','lab'),
('122','Vancomycin trough > 25','NULL','NULL'),
('123','Vitamin K administration','NULL','NULL'),
('124','Any ED or hospital admission within 90 days of surgery with implantable devices Trigger','Readmission','readmission'),
('125','Decrease in PTT >50% and administration of Heparin Trigger','Coagulation','lab-prereq-prereq'),
('126','Administration of Prothrombin Complex Trigger','Coagulation','medication'),
('127','Administration of Glucagon','Glycemic','medication'),
('128','Administration of Coagulation Factor VIIa Trigger','Coagulation','medication'),
('129','Administration of Dextrose 50% Trigger','Glycemic','medication'),
('130','Glucose < 70 and > 40 Trigger','Glycemic','lab'),
('131','Heparin-induced Thrombocytopenia Trigger','Coagulation','lab'),
('132','Administration of Ephedrine Trigger','Perinatal','medication'),
('133','Radiology Study for Emboli or DVT within 30 days after surgery','Coagulation','event-prereq-event'),
('134','Cord Blood Gas pH < 7.1 Trigger','Perinatal','lab'),
('135','3rd or 4th degree vaginal laceration after delivery','Perinatal','patient-care'),
('136','Any code or activation of rapid response team','Patient Care','patient-care'),
('137','Sepsis Indicator: Lactate and BUN','Patient Care','lab-lab'),
('138','Possible Acute Kidney Injury','Renal Injury','lab-lab'),
('139','Increase in Serum Creatinine >20% from baseline in last 30 hours','Renal Injury','lab-lab'),
('140','Nephrotoxic Medication Exposure (3 separate meds)','Renal Injury','med-med-med'),
('141','Positive Healthcare Associated CephR','Healthcare Associated Infections','NULL'),
('142','Possible Healthcare Associated CRE Infection','Healthcare Associated Infections','NULL'),
('143','Possible Healthcare Associated MDR-Acinetobacter infection','Healthcare Associated Infections','NULL'),
('144','Possible Hospita-Acquired MRSA Infection','Healthcare Associated Infections','NULL'),
('145','Possible Hospital- Acquired MRSA Lab Screen','Healthcare Associated Infections','NULL'),
('146','Possible Healthcare-associated VRE infection','Healthcare Associated Infections','NULL'),
('147','Possible Healthcare- associated VRE lab screen','Healthcare Associated Infections','NULL'),
('148','Nephrotoxic Medication Exposure within 48 Hours','Renal Injury','med-med-med'),
('149','Administration of Tranexamic Acid','NULL','medication'),
('150','Infiltrations: Nurse Documentation or Vesicant Reversal Administration','Pediatric','medication'),
('151','Opioid MME >100','Pain Management','medication')

